// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaummzpllzbrluajybmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhdW1tenBsbHpicmx1YWp5Ym1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTUwMDUsImV4cCI6MjA1ODgzMTAwNX0.izZ-WVNsuMW8mQooDF9cTDc6qx0rUwfsoQJYINrSA3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);